package br.gov.mti.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SolicitacaoDiariaRejeitada implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SolicitacaoDiariaRejeitada() {
    }

}