package br.gov.mti.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SolicitacaoDiaria implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Funcionario")
   private br.gov.mti.poc.Funcionario funcionario;

   @org.kie.api.definition.type.Label("Data da Solicitacao")
   private java.util.Date dataSolicitacao = new java.util.Date();;

   @org.kie.api.definition.type.Label(value = "Tipo da Solicitacao")
   private java.lang.String tipoSolicitacao;

   public SolicitacaoDiaria()
   {
   }
   
   public SolicitacaoDiaria(Funcionario funcionario, java.util.Date dataSolicitacao) {
       this.setFuncionario(funcionario);
       this.setDataSolicitacao(dataSolicitacao);
   }

   public br.gov.mti.poc.Funcionario getFuncionario()
   {
      return this.funcionario;
   }

   public void setFuncionario(br.gov.mti.poc.Funcionario funcionario)
   {
      this.funcionario = funcionario;
   }

   public java.util.Date getDataSolicitacao()
   {
      return this.dataSolicitacao;
   }

   public void setDataSolicitacao(java.util.Date dataSolicitacao)
   {
      this.dataSolicitacao = dataSolicitacao;
   }

   public java.lang.String getTipoSolicitacao()
   {
      return this.tipoSolicitacao;
   }

   public void setTipoSolicitacao(java.lang.String tipoSolicitacao)
   {
      this.tipoSolicitacao = tipoSolicitacao;
   }

   public SolicitacaoDiaria(br.gov.mti.poc.Funcionario funcionario,
         java.util.Date dataSolicitacao, java.lang.String tipoSolicitacao)
   {
      this.funcionario = funcionario;
      this.dataSolicitacao = dataSolicitacao;
      this.tipoSolicitacao = tipoSolicitacao;
   }

}