package br.gov.mti.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StatusSolicitanteSistemasExternos implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Status TSE")
   private java.lang.String statusTSE;
   @org.kie.api.definition.type.Label("Status Receita Federal")
   private java.lang.String statusReceitaFederal;

   @org.kie.api.definition.type.Label(value = "Status")
   private java.lang.String status;

   public StatusSolicitanteSistemasExternos()
   {
   }

   public java.lang.String getStatusTSE()
   {
      return this.statusTSE;
   }

   public void setStatusTSE(java.lang.String statusTSE)
   {
      this.statusTSE = statusTSE;
   }

   public java.lang.String getStatusReceitaFederal()
   {
      return this.statusReceitaFederal;
   }

   public void setStatusReceitaFederal(java.lang.String statusReceitaFederal)
   {
      this.statusReceitaFederal = statusReceitaFederal;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public StatusSolicitanteSistemasExternos(java.lang.String statusTSE,
         java.lang.String statusReceitaFederal, java.lang.String status)
   {
      this.statusTSE = statusTSE;
      this.statusReceitaFederal = statusReceitaFederal;
      this.status = status;
   }

}