package br.gov.mti.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Funcionario implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Nome")
   private java.lang.String nome;
   @org.kie.api.definition.type.Label("CPF")
   private java.lang.String cpf;
   @org.kie.api.definition.type.Label("Email")
   private java.lang.String email;
   @org.kie.api.definition.type.Label("Idade")
   private java.lang.Integer idade;
   @org.kie.api.definition.type.Label("Unidade Organizacional")
   private java.lang.String unidade;

   public Funcionario()
   {
   }

   public java.lang.String getNome()
   {
      return this.nome;
   }

   public void setNome(java.lang.String nome)
   {
      this.nome = nome;
   }

   public java.lang.String getCpf()
   {
      return this.cpf;
   }

   public void setCpf(java.lang.String cpf)
   {
      this.cpf = cpf;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.Integer getIdade()
   {
      return this.idade;
   }

   public void setIdade(java.lang.Integer idade)
   {
      this.idade = idade;
   }
   
   public java.lang.String getUnidade()
   {
      return this.unidade;
   }

   public void setUnidade(java.lang.String unidade)
   {
      this.unidade = unidade;
   }

   public Funcionario(java.lang.String nome, java.lang.String cpf,
         java.lang.String email, java.lang.Integer idade)
   {
      this.nome = nome;
      this.cpf = cpf;
      this.email = email;
      this.idade = idade;
   }

}